[theme]
base="light"  # Ou "dark" para o modo escuro
primaryColor="#1f77b4"  # Cor primária (exemplo: azul)
secondaryBackgroundColor="#f0f0f5"  # Cor de fundo secundária
backgroundColor="#ffffff"  # Cor de fundo principal (branco para light mode)
textColor="#000000"  # Cor do texto (preto para o light mode)
